from app.core.exceptions.service_exceptions.user.user import (
    UserNotFoundException,
)